
kind: Namespace
apiVersion: v1
metadata:
  name: resyncz-ns
  labels:
    name: resyncz-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rankr-depl
  namespace: resyncz-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rankr
  template:
    metadata:
      labels:
        app: rankr
    spec:
      containers:
        - name: rankr-svc
          image: semirm/rankr-svc:4
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 100Mi
            requests:
              cpu: 250m
              memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: rankr-clusterip-svc
  namespace: resyncz-ns
spec:
  type: ClusterIP
  selector:
    app: rankr
  ports:
    - protocol: "TCP"
      port: 8081
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rankr-ingress-svc
  namespace: resyncz-ns
spec:
  rules:
    - host: rankr-svc.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rankr-clusterip-svc
                port:
                  number: 8081