version: "3"
services:
  notifi:
    image: semirm/rankr-svc:4
    container_name: rankr_svc
    ports:
      - "8080:8080"
    depends_on:
      - elastic
    networks:
      - notif_elastic
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    container_name: elastic
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - elasticdata:/usr/share/elasticsearch/data
    networks:
      - notif_elastic
volumes:
  elasticdata:
    driver: local
networks:
  notif_elastic: